name: Build and Deploy to production
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Install dependencies and building application for production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on branch
        uses: actions/checkout@master

      - name: Installing Node
        uses: actions/setup-node@master

      - name: Installing application dependencies
        run: npm install

      - name: Building the application
        run: npm run build

      - name: Upload dist directory as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
      name: Deploy the application on AWS S3
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download dist directory artifact
          uses: actions/download-artifact@v2
          with:
            name: dist
            path: dist
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env: 
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: dist